services:
  aisolver:
    build:
      context: https://github.com/sourav3688/ai-solver-server.git
    container_name: ai-solver-serv
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=gpt-5.2
